// Drives PearTune on the iPhone Simulator, so the App Review demo video can be recorded
// without a human tapping (proposal 2026-07-28-app-review-demo, the "demo video" half).
//
// WHY A UI TEST AND NOT A SCRIPT. Driving the Simulator from OUTSIDE needs macOS
// Accessibility permission, which an ssh session cannot be granted without someone sitting
// at the machine. XCUITest runs INSIDE the simulator via testmanagerd and needs no such
// grant, so this works headlessly over ssh - which is the whole point.
//
// It attaches to the ALREADY-INSTALLED app by bundle id rather than being a target inside
// the PearTune Xcode project. ios/ is generated by `expo prebuild`, so a test target added
// there would vanish on the next regeneration; this project is standalone and outlives it.
//
// PACING IS DELIBERATE. Every step sleeps longer than it needs to. This is filmed, not
// asserted - a viewer has to be able to read the screen before it changes, and a cut that
// lands mid-transition looks like a glitch rather than a feature.

import XCTest

final class DemoFlow: XCTestCase {

  let app = XCUIApplication(bundleIdentifier: "com.peartune")

  override func setUp() {
    super.setUp()
    // Keep going after a miss so one run reports EVERY step that failed, not just the
    // first. Each helper dumps the hierarchy on a miss, so a single run says what changed.
    continueAfterFailure = true
  }

  // Wait for a button and tap it, then hold for the camera.
  private func tap (_ label: String, wait: TimeInterval = 25, hold: UInt32 = 3, line: UInt = #line) {
    let b = app.buttons[label]
    if !b.waitForExistence(timeout: wait) {
      XCTFail("no button '\(label)' after \(wait)s", line: line)
      print("=== HIERARCHY AT MISS (\(label)) ===\n\(app.debugDescription)\n=== END ===")
      return
    }
    b.tap()
    sleep(hold)
  }

  // Tap by position instead of by name. The album grid and the track rows are DIV-based
  // React nodes, not <button>s, so accessibility publishes them as generic elements with no
  // stable label to address - a normalized coordinate is the honest way to reach them.
  private func tapAt (_ dx: CGFloat, _ dy: CGFloat, hold: UInt32 = 3) {
    app.coordinate(withNormalizedOffset: CGVector(dx: dx, dy: dy)).tap()
    sleep(hold)
  }

  // THE SHOT. Cold launch -> named -> demo library -> browse -> play -> the player.
  func testRecordDemoFlow () {
    app.launch()
    sleep(18) // the Bare worklet boots, then the WebView loads its bundle

    // 1. The intro: what PearTune even is.
    sleep(4)
    tap("Get started")

    // 2. Who is this? The name reaches the operator's dashboard on a real pair, and it is
    //    asked BEFORE the demo is offered so a demo user is never anonymous.
    let field = app.textFields.firstMatch
    if field.waitForExistence(timeout: 20) {
      field.tap()
      sleep(1)
      app.typeText("Alex")
      sleep(2)
      // The keyboard covers Continue. Tapping the heading dismisses it without changing state.
      tapAt(0.5, 0.18, hold: 2)
    } else {
      XCTFail("no name field")
      print("=== HIERARCHY AT MISS (name field) ===\n\(app.debugDescription)\n=== END ===")
    }
    tap("Continue")

    // 3. Where is your music? Three honest answers, and the reviewer has none of the first two.
    sleep(3)
    tap("I don’t have one yet", hold: 2) // curly apostrophe: it is what the UI renders

    // 4. The bundled library appears. This is the beat that matters - no pairing, no server,
    //    no network. Long hold: the copy on the banner is the explanation.
    sleep(22)

    // 5. Browse. The album tile sits under the demo banner in the grid.
    tapAt(0.26, 0.62, hold: 4)

    // 6. Play the album.
    tap("Play", hold: 6)

    // 7. Open the full player and let it run, so the transport and the artwork are on screen.
    //    dy 0.85 is the MINI-PLAYER row; 0.90 was the tab bar underneath it, which is how an
    //    earlier take ended up filming the Queue screen. dx 0.4 stays off the pause button.
    tapAt(0.4, 0.85, hold: 10)

    print("=== FLOW COMPLETE ===")
  }
}
