// The iOS version has THREE sources of truth and only one of them ships.
//
// app.json is what the release script bumps. ios/PearTune.xcodeproj/project.pbxproj
// carries MARKETING_VERSION / CURRENT_PROJECT_VERSION. And ios/PearTune/Info.plist
// carries CFBundleShortVersionString / CFBundleVersion as LITERAL values, because
// that is what `expo prebuild` writes - not $(MARKETING_VERSION) references.
//
// Info.plist is the one that ends up in the IPA. So it can disagree with both of the
// others and the build will happily archive, sign, export and upload something no
// other file in the tree describes.
//
// WHICH IS EXACTLY WHAT HAPPENED, 2026-08-17. The 1.0.2 release had app.json at
// 1.0.2 build 5 and project.pbxproj at MARKETING_VERSION 1.0.2 /
// CURRENT_PROJECT_VERSION 5 on BOTH the Linux box and the Mac mini - and still
// produced an IPA stamped 1.0.1 build 3, because Info.plist was a snapshot from the
// last prebuild and step 0 only ever sed'd the pbxproj. App Store Connect already
// held build 3 in the 1.0.1 train and rejected it:
//
//   The bundle version must be higher than the previously uploaded version.
//
// The archive, the signing and the export all "succeeded". Nothing between the bump
// and Apple's own uniqueness check looked at what was actually in the bundle.
//
// Step 0 now syncs Info.plist as well, so this guard has something that satisfies it
// rather than being a wall across the release path.
//
// NO LONGER SKIPS. Until 2026-08-18 these tests skipped when ios/ was absent, on the
// stated grounds that "unlike android/, ios/ is NOT committed here". That was true of
// eighteen files and false of the nineteenth: project.pbxproj alone was tracked, so
// the directory was neither committed nor ignored, and Info.plist - the file Apple
// reads - was invisible to review and to a fresh clone. That ambiguity is how the
// 2026-08-17 bug survived: everyone reasoned about ios/ as disposable generated
// output, so nobody asked which file the IPA actually reads. ios/ is now committed in
// full, the same way android/ is, and these guards run unconditionally. See
// DECISIONS.md 2026-08-18.
//
// The cost of committing generated output is drift: ios/ is regenerated by
// `expo prebuild` from app.json, and the release script only prebuilds when ios/ is
// MISSING, so on any tree that already has it the native files are a snapshot. Edit
// app.json's ios block without prebuilding and the archive keeps the old values. The
// last test below is what notices.

const test = require('node:test')
const assert = require('node:assert')
const fs = require('node:fs')
const path = require('node:path')
const iosDir = path.join(__dirname, '..', 'ios')
const plist = path.join(iosDir, 'PearTune', 'Info.plist')
const pbxproj = path.join(iosDir, 'PearTune.xcodeproj', 'project.pbxproj')
const app = require(path.join(__dirname, '..', 'app.json')).expo

// Read a <key>NAME</key> followed by its <string>VALUE</string>. Deliberately the
// same shape the release script's sed targets, so the test fails if that sed ever
// stops matching the file it is meant to edit.
function plistString (text, key) {
  const m = text.match(new RegExp(`<key>${key}</key>\\s*<string>([^<]*)</string>`))
  return m ? m[1] : null
}

test('the two files an iOS archive actually reads are committed', () => {
  assert.ok(
    fs.existsSync(pbxproj),
    'ios/PearTune.xcodeproj/project.pbxproj is missing. ios/ is committed in this repo ' +
    '(see DECISIONS.md 2026-08-18) - it is generated by `expo prebuild` but the generated ' +
    'tree lives in git, exactly like android/. Run `npx expo prebuild -p ios` and commit.'
  )
  assert.ok(
    fs.existsSync(plist),
    'ios/PearTune/Info.plist is missing. This is the file whose literal values decide what ' +
    'App Store Connect receives, and it is committed for that reason.'
  )
})

test('ios Info.plist version matches app.json (it is the one that ships)', () => {
  const text = fs.readFileSync(plist, 'utf8')

  assert.equal(
    plistString(text, 'CFBundleShortVersionString'), app.version,
    'Info.plist CFBundleShortVersionString disagrees with app.json. This is the value that ' +
    'ends up in the IPA, so the upload would carry a version nothing else in the tree claims. ' +
    'Release step 0 syncs this; if it drifted, that sync did not run or stopped matching.'
  )
  assert.equal(
    plistString(text, 'CFBundleVersion'), String(app.ios.buildNumber),
    'Info.plist CFBundleVersion disagrees with app.json.expo.ios.buildNumber. App Store Connect ' +
    'rejects a build number it has already seen for a version train, which is how this last ' +
    'surfaced - after a full archive, sign and export.'
  )
})

test('ios project.pbxproj version matches app.json', () => {
  const text = fs.readFileSync(pbxproj, 'utf8')
  const marketing = [...text.matchAll(/MARKETING_VERSION = ([0-9][0-9.]*);/g)].map(m => m[1])
  const current = [...text.matchAll(/CURRENT_PROJECT_VERSION = ([0-9]+)/g)].map(m => m[1])

  assert.ok(marketing.length > 0, 'no MARKETING_VERSION found - the step 0 sed would be a no-op')
  assert.ok(current.length > 0, 'no CURRENT_PROJECT_VERSION found - the step 0 sed would be a no-op')

  // Every occurrence, not just the first: the sed uses /g and a target left behind
  // would be the one an archive picks up.
  for (const v of marketing) assert.equal(v, app.version, 'a MARKETING_VERSION disagrees with app.json')
  for (const v of current) assert.equal(v, String(app.ios.buildNumber), 'a CURRENT_PROJECT_VERSION disagrees with app.json')
})

test('ios project.pbxproj bundle identifier matches app.json', () => {
  const text = fs.readFileSync(pbxproj, 'utf8')
  const ids = [...text.matchAll(/PRODUCT_BUNDLE_IDENTIFIER = "?([^";]+)"?;/g)].map(m => m[1])

  assert.ok(ids.length > 0, 'no PRODUCT_BUNDLE_IDENTIFIER found in the committed project')
  // Both the Debug and Release configurations, so a half-renamed app cannot archive
  // under one identifier and run under another.
  for (const id of ids) {
    assert.equal(
      id, app.ios.bundleIdentifier,
      'a PRODUCT_BUNDLE_IDENTIFIER disagrees with app.json.expo.ios.bundleIdentifier. ' +
      'Nothing in the release path re-derives this, so a rename in app.json alone ships the old id.'
    )
  }
})

// The drift guard that the version checks above do not cover.
//
// app.json's expo.ios.infoPlist is the SOURCE for the permission strings, the audio
// background mode and the loopback ATS exception. `expo prebuild` copies them into
// Info.plist - but only when it runs, and the release script runs it only when ios/ is
// absent, which it now never is. So adding NSLocalNetworkUsageDescription (say) to
// app.json and shipping without a prebuild would produce an app that silently lacks the
// entitlement it claims. Assert every declared key actually reached the plist.
test('every key app.json declares under ios.infoPlist reached the committed Info.plist', () => {
  const text = fs.readFileSync(plist, 'utf8')
  const declared = app.ios.infoPlist || {}

  assert.ok(
    Object.keys(declared).length > 0,
    'app.json declares no expo.ios.infoPlist keys - if that is deliberate, delete this test ' +
    'rather than leaving a guard with nothing to check.'
  )

  for (const [key, value] of Object.entries(declared)) {
    const stale =
      `app.json declares ios.infoPlist.${key} but the committed Info.plist does not match. ` +
      'ios/ is generated output that lives in git, so an app.json edit does not reach the ' +
      'archive on its own: run `npx expo prebuild -p ios` and commit the result.'

    assert.ok(new RegExp(`<key>${key}</key>`).test(text), stale)

    if (typeof value === 'string') {
      assert.equal(plistString(text, key), value, stale)
    } else if (typeof value === 'boolean') {
      assert.ok(new RegExp(`<key>${key}</key>\\s*<${value}/>`).test(text), stale)
    } else if (Array.isArray(value)) {
      const block = text.match(new RegExp(`<key>${key}</key>\\s*<array>([\\s\\S]*?)</array>`))
      assert.ok(block, stale)
      for (const entry of value) {
        assert.ok(block[1].includes(`<string>${entry}</string>`), stale + ` (missing ${entry})`)
      }
    }
    // Nested dicts (NSAppTransportSecurity) are checked for presence only. Their shape
    // is Apple's, not ours, and a structural comparison here would re-implement a plist
    // parser to catch a case prebuild has never got wrong.
  }
})
