// The committed android/ tree must agree with the config plugins that generate it.
//
// android/ is BOTH committed and regenerated by `expo prebuild`, so the two WebView-recovery
// .kt files are generated output that also lives in git. That is a normal prebuild-and-commit
// setup with one silent failure mode in each direction:
//
//   - edit the .kt in android/ (the obvious place to look) and the next prebuild overwrites it
//   - edit the plugin and forget to prebuild+commit, and every plain `./gradlew assembleDebug`
//     keeps building the OLD module while the source says otherwise
//
// Either way the build is green and the device is wrong, which is exactly the shape of the bug
// that killed playback on 2026-07-22 (a patch that applied cleanly and was never compiled in).
// So: assert they agree, and make `npm run verify` the thing that notices.

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const { MODULE_KT, PACKAGE_KT, REGISTER_CALL } = require('../plugins/webview-recovery-source')

const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'app.json'), 'utf8')).expo?.android?.package
const nativeDir = () => path.join(ROOT, 'android/app/src/main/java', ...String(pkg).split('.'))
const read = (f) => fs.readFileSync(path.join(nativeDir(), f), 'utf8')

test('app.json still names the android package the generated sources are written under', () => {
  assert.ok(pkg, 'app.json has expo.android.package')
  assert.ok(fs.existsSync(nativeDir()), 'the committed native dir for ' + pkg + ' exists')
})

test('the committed WebViewRecoveryModule.kt is byte-identical to what the plugin writes', () => {
  assert.equal(
    read('WebViewRecoveryModule.kt'),
    MODULE_KT(pkg),
    'android/…/WebViewRecoveryModule.kt has drifted from plugins/webview-recovery-source.js. ' +
    'The plugin is the source: edit it, run `npx expo prebuild -p android`, and commit the result.'
  )
})

test('the committed WebViewRecoveryPackage.kt is byte-identical to what the plugin writes', () => {
  assert.equal(
    read('WebViewRecoveryPackage.kt'),
    PACKAGE_KT(pkg),
    'android/…/WebViewRecoveryPackage.kt has drifted from plugins/webview-recovery-source.js.'
  )
})

test('MainApplication.kt registers the package EXACTLY once', () => {
  const main = read('MainApplication.kt')
  const hits = main.split(REGISTER_CALL).length - 1
  // Zero means the recovery module is dead code and the GrapheneOS freeze is back. Two means RN
  // throws on the duplicate module name at launch - a crash, not a warning.
  assert.equal(hits, 1, `expected exactly one ${REGISTER_CALL} in MainApplication.kt, found ${hits}`)
})

// --- with-android-queries: idempotency, the hard way ---------------------------
//
// That plugin used to `push()` its <queries> block unconditionally. android/ is committed
// AND regenerated, so every `expo prebuild` appended another identical copy: the committed
// manifest had reached NINE of them, and each prebuild produced a spurious 18-line diff on
// a file nobody had touched. The plugin now drops any pre-existing copy before adding its
// own; this notices if that regresses, or if a hand-merge duplicates it.
test('the committed AndroidManifest declares our <queries> intents exactly once', () => {
  const xml = fs.readFileSync(path.join(ROOT, 'android/app/src/main/AndroidManifest.xml'), 'utf8')
  for (const scheme of ['lightning', 'bitcoin', 'mailto']) {
    const hits = xml.split(`android:scheme="${scheme}"`).length - 1
    assert.equal(hits, 1, `expected one ${scheme} query intent in AndroidManifest.xml, found ${hits} ` +
      '- with-android-queries has duplicated its block again (run a prebuild and commit the result)')
  }
})
