// The committed android/app/build.gradle must carry what the release build needs.
//
// Same shape of guard as prebuild.test.js, for the same reason: android/ is BOTH
// committed and regenerated by `expo prebuild`, so build.gradle is generated output
// that also lives in git. Two silent failure modes, one in each direction:
//
//   - edit build.gradle directly and the next prebuild wipes it
//   - edit the plugin and forget to prebuild+commit, and every plain `./gradlew
//     assembleRelease` keeps using the OLD gradle while the source says otherwise
//
// What makes this worth a test rather than a comment is what the two plugins buy:
//
//   with-android-release-signing   without it, buildTypes.release points at
//                                  signingConfigs.debug, so assembleRelease
//                                  produces a DEBUG-SIGNED "release" APK. It
//                                  builds, it installs, and publishing it once
//                                  binds the app's Play and Zapstore identity to
//                                  a throwaway key, permanently.
//
//   with-android-version-from-env  without it, the release bumps app.json but
//                                  build.gradle keeps the version from the last
//                                  prebuild, so the APK ships a stale version
//                                  while the tag and the announcement say the new
//                                  one. Play rejects the duplicate versionCode;
//                                  Zapstore publishes it happily.
//
// Neither failure is visible in a green build, which is exactly why they belong in
// `npm run verify`.

const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const GRADLE = path.join(ROOT, 'android/app/build.gradle')

const { RELEASE_SIGNING_CONFIG_SENTINEL } = require('../plugins/with-android-release-signing')
const { VERSION_SENTINEL } = require('../plugins/with-android-version-from-env')

const gradle = () => fs.readFileSync(GRADLE, 'utf8')

const hint = (plugin) =>
  `The plugin is the source: edit plugins/${plugin}.js, run ` +
  '`npx expo prebuild -p android`, and commit the result.'

test('app.json registers both release-build plugins', () => {
  const plugins = JSON.parse(fs.readFileSync(path.join(ROOT, 'app.json'), 'utf8')).expo.plugins
  for (const p of ['./plugins/with-android-release-signing', './plugins/with-android-version-from-env']) {
    assert.ok(plugins.includes(p), `app.json expo.plugins is missing ${p}`)
  }
})

test('build.gradle declares a release signingConfig that reads the keystore from the env', () => {
  const src = gradle()
  assert.match(src, /signingConfigs\s*\{[\s\S]*\brelease\s*\{/,
    'no `release` block inside signingConfigs. ' + hint('with-android-release-signing'))
  assert.ok(src.includes(RELEASE_SIGNING_CONFIG_SENTINEL),
    'the release signingConfig does not read KEYSTORE_FILE from the environment. ' +
    hint('with-android-release-signing'))
  for (const key of ['KEYSTORE_FILE', 'KEYSTORE_PASSWORD', 'KEY_ALIAS', 'KEY_PASSWORD']) {
    assert.ok(src.includes(`"${key}"`), `the release signingConfig never reads ${key}`)
  }
})

test('buildTypes.release does NOT unconditionally sign with the debug keystore', () => {
  // The Expo template ships `signingConfig signingConfigs.debug` here. The plugin
  // turns it into a ternary that prefers the real keystore when one is configured.
  // Anchored on the template's own comment, which identifies the release buildType
  // rather than the debug one.
  const m = gradle().match(
    /see https:\/\/reactnative\.dev\/docs\/signed-apk-android\.\n\s*signingConfig (.+)/
  )
  assert.ok(m, 'could not find the release buildType signingConfig line in build.gradle')
  assert.notEqual(m[1].trim(), 'signingConfigs.debug',
    'buildTypes.release still signs with the DEBUG keystore unconditionally - a release ' +
    'APK built from this tree would be debug-signed. ' + hint('with-android-release-signing'))
  assert.match(m[1], /signingConfigs\.release/,
    'buildTypes.release never mentions signingConfigs.release. ' +
    hint('with-android-release-signing'))
})

test('build.gradle lets APP_VERSION / APP_VERSION_CODE override the prebuilt version', () => {
  const src = gradle()
  assert.ok(src.includes(VERSION_SENTINEL),
    'build.gradle does not read APP_VERSION from the environment, so a release would ' +
    'ship the version from the last prebuild. ' + hint('with-android-version-from-env'))
  assert.match(src, /if \(envAppVersion\) \{ versionName envAppVersion/,
    'the versionName override is missing. ' + hint('with-android-version-from-env'))
  assert.match(src, /if \(envAppVersionCode\) \{ versionCode envAppVersionCode/,
    'the versionCode override is missing. ' + hint('with-android-version-from-env'))
})

test('the env override comes AFTER the literal version lines Expo owns', () => {
  // Order is load-bearing, not cosmetic. Expo's own version mod rewrites the
  // FIRST `versionCode.*` and `versionName.*` it finds on every prebuild. With
  // the override placed first, prebuild #2 overwrites it and leaves a
  // half-patched block - measured 2026-07-29, `versionCode 1` came back while
  // the versionName override survived. Keeping the literals first means Expo
  // rewrites only what it owns and this plugin stays idempotent.
  const src = gradle()
  const literal = src.search(/^ +versionName "[^"]*"$/m)
  const override = src.indexOf(VERSION_SENTINEL)
  assert.ok(literal !== -1, 'build.gradle no longer has a literal versionName line')
  assert.ok(override !== -1, 'build.gradle no longer has the env override')
  assert.ok(literal < override,
    'the APP_VERSION override sits ABOVE the literal versionCode/versionName lines. ' +
    "Expo's version mod rewrites the first occurrence of each, so the next prebuild " +
    'will clobber the override. Move it below them.')
})
