package com.peartune

// GENERATED by plugins/with-webview-recovery.js - do not edit here, edit the plugin.

import android.view.View
import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ReactShadowNode
import com.facebook.react.uimanager.ViewManager

class WebViewRecoveryPackage : ReactPackage {
    override fun createNativeModules(ctx: ReactApplicationContext): List<NativeModule> =
        listOf(WebViewRecoveryModule(ctx))

    override fun createViewManagers(ctx: ReactApplicationContext): List<ViewManager<View, ReactShadowNode<*>>> =
        emptyList()
}
