#!/usr/bin/env bash
# iOS App Store archive + upload. Runs ON the Mac mini, not over here.
#
# scripts/release.sh step 11 rsyncs the tree to the Mac, rebuilds the bundles
# there, runs pod install, then ssh's in and calls this. It is also runnable by
# hand on the Mac:
#
#   cd ~/peartune-ios && ./scripts/ios-appstore.sh
#
# Required env vars (or set in scripts/.env) - one of these auth methods:
#
#   Preferred (API key via asc CLI):
#     ASC_KEY_ID           - App Store Connect API key ID
#     ASC_ISSUER_ID        - App Store Connect API issuer ID
#     ASC_APP_ID           - Numeric App Store app ID (from `asc apps list`)
#     ASC_PRIVATE_KEY_PATH - Path to .p8 key (default: ~/.appstoreconnect/AuthKey_<KEY_ID>.p8)
#
#   Legacy (app-specific password via altool):
#     ASC_APPLE_ID         - Apple ID email
#     ASC_APP_PASSWORD     - App-specific password (appleid.apple.com -> App-Specific Passwords)
#
# Optional env vars:
#   ASC_TEAM_ID        - Team ID (default: G79ALD29NA)
#   ARCHIVE_PATH       - Path to an existing .xcarchive to skip the rebuild

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load app config and env
if [ -f "$SCRIPT_DIR/app.conf" ]; then
  set -a; source "$SCRIPT_DIR/app.conf"; set +a
fi
if [ -f "$SCRIPT_DIR/.env" ]; then
  set -a; source "$SCRIPT_DIR/.env"; set +a
fi

: "${APP_NAME:?APP_NAME is not set - check scripts/app.conf}"
: "${BUNDLE_ID:?BUNDLE_ID is not set - check scripts/app.conf}"

# ios/ is generated, not committed. If the rsync brought no project there is
# nothing to archive, and saying so beats a wall of xcodebuild output.
if [ ! -f "$REPO_ROOT/${XCODE_WORKSPACE}" ] && [ ! -d "$REPO_ROOT/${XCODE_WORKSPACE}" ]; then
  echo "Error: $REPO_ROOT/${XCODE_WORKSPACE} not found." >&2
  echo "  ios/ is generated by \`expo prebuild -p ios\` and is not committed in this repo," >&2
  echo "  so it has to exist on the machine that rsyncs to this one." >&2
  exit 1
fi

# ── Determine upload method ─────────────────────────────────────────────────
# Prefer asc CLI (API key auth), fall back to altool (app-specific password)
USE_ASC=false
if command -v asc &>/dev/null \
   && [ -n "${ASC_KEY_ID:-}" ] \
   && [ -n "${ASC_ISSUER_ID:-}" ] \
   && [ -n "${ASC_APP_ID:-}" ]; then
  USE_ASC=true
  echo "Upload method: asc CLI (API key auth)"
elif [ -n "${ASC_APPLE_ID:-}" ] && [ -n "${ASC_APP_PASSWORD:-}" ]; then
  echo "Upload method: altool (app-specific password, legacy)"
else
  echo "Error: No upload credentials configured."
  echo "  Option A (preferred): Install 'asc' and set ASC_KEY_ID, ASC_ISSUER_ID, ASC_APP_ID"
  echo "  Option B (legacy):    Set ASC_APPLE_ID and ASC_APP_PASSWORD"
  exit 1
fi

TEAM_ID="${ASC_TEAM_ID:-G79ALD29NA}"
ARCHIVE_PATH="${ARCHIVE_PATH:-/tmp/${APP_NAME}.xcarchive}"
EXPORT_PATH="/tmp/${APP_NAME}-appstore"
EXPORT_OPTIONS="/tmp/${APP_NAME}-ExportOptions.plist"

# ── Write ExportOptions.plist ───────────────────────────────────────────────
cat > "$EXPORT_OPTIONS" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key>
  <string>app-store-connect</string>
  <key>teamID</key>
  <string>${TEAM_ID}</string>
  <key>provisioningProfiles</key>
  <dict>
    <key>${BUNDLE_ID}</key>
    <string>${IOS_PROVISIONING_PROFILE}</string>
  </dict>
  <key>signingCertificate</key>
  <string>Apple Distribution</string>
  <key>signingStyle</key>
  <string>manual</string>
  <key>uploadSymbols</key>
  <false/>
</dict>
</plist>
EOF

# ── Unlock the signing keychain and grant codesign access ───────────────────
# THE ONE THAT COSTS AN AFTERNOON. codesign over ssh dies with
# errSecInternalComponent at the embed-frameworks phase - AFTER all of arm64 has
# compiled, ~10 minutes in - unless the keychain holding the private key is
# unlocked AND that key's ACL grants codesign non-interactive use.
#
# It is NOT the login keychain. This Mac has a dedicated buildkey.keychain that
# comes FIRST in the search list, and that is the one codesign resolves the
# identity from; unlocking login.keychain-db changes nothing and fails
# identically every time. The tell is that `security find-identity -v` lists
# every identity TWICE, once per keychain. (Same trap, same fix, as
# scripts/ios-device-build.sh - read its comment before touching this.)
#
# Empty password by convention, shared with the sibling apps. Nothing here
# should ever ask for one.
#   unlock-keychain         allows access in this session
#   list-keychains -s       makes it visible to child processes
#   set-key-partition-list  grants apple-tool/codesign access to private keys
security unlock-keychain -p "" ~/Library/Keychains/buildkey.keychain
security list-keychains -s \
  ~/Library/Keychains/buildkey.keychain \
  ~/Library/Keychains/login.keychain-db \
  /Library/Keychains/System.keychain
security set-key-partition-list \
  -S apple-tool:,apple:,codesign: \
  -s -k "" \
  ~/Library/Keychains/buildkey.keychain

# ── Xcode PATH ─────────────────────────────────────────────────────────────
# Xcode's distribution pipeline invokes rsync internally. If Homebrew's GNU
# rsync (3.4.x) is on PATH it conflicts with Apple's built-in openrsync and
# causes "Copy failed" during IPA packaging. Strip /opt/homebrew/bin from PATH
# for the xcodebuild invocations so the system rsync is found instead.
XCODE_PATH=$(printf '%s' "$PATH" | sed 's|/opt/homebrew/bin:||g; s|:/opt/homebrew/bin||g')

# ── Archive ─────────────────────────────────────────────────────────────────
rm -rf "$ARCHIVE_PATH"
echo "Archiving..."
PATH="$XCODE_PATH" xcodebuild \
  -workspace "$REPO_ROOT/${XCODE_WORKSPACE}" \
  -scheme "$XCODE_SCHEME" \
  -configuration Release \
  -destination "generic/platform=iOS" \
  -archivePath "$ARCHIVE_PATH" \
  DEVELOPMENT_TEAM="$TEAM_ID" \
  OTHER_CODE_SIGN_FLAGS="--keychain ~/Library/Keychains/buildkey.keychain" \
  archive | grep -E "^(error:|warning:|note:|.*ARCHIVE)" || true

if [ ! -d "$ARCHIVE_PATH" ]; then
  echo "Error: archive failed - no .xcarchive at $ARCHIVE_PATH" >&2
  exit 1
fi
echo "Archive complete: $ARCHIVE_PATH"

# ── Export ──────────────────────────────────────────────────────────────────
echo "Exporting..."
rm -rf "$EXPORT_PATH"
PATH="$XCODE_PATH" xcodebuild \
  -exportArchive \
  -archivePath "$ARCHIVE_PATH" \
  -exportPath "$EXPORT_PATH" \
  -exportOptionsPlist "$EXPORT_OPTIONS" \
  2>&1 | grep -v "^2[0-9][0-9][0-9]-" || true  # suppress timestamp lines

IPA_PATH=$(find "$EXPORT_PATH" -name "*.ipa" | head -1)
if [ -z "$IPA_PATH" ]; then
  echo "Error: export failed - no .ipa found in $EXPORT_PATH" >&2
  exit 1
fi
echo "Export complete: $IPA_PATH"

# ── Upload ──────────────────────────────────────────────────────────────────
echo "Uploading to App Store Connect..."
if $USE_ASC; then
  ASC_KEY_FILE="${ASC_PRIVATE_KEY_PATH:-$HOME/.appstoreconnect/AuthKey_${ASC_KEY_ID}.p8}"
  asc auth login \
    --bypass-keychain \
    --name "${APP_NAME}-CI" \
    --key-id "$ASC_KEY_ID" \
    --issuer-id "$ASC_ISSUER_ID" \
    --private-key "$ASC_KEY_FILE"

  asc builds upload --app "$ASC_APP_ID" --ipa "$IPA_PATH"
else
  xcrun altool \
    --upload-app \
    --type ios \
    --file "$IPA_PATH" \
    --username "$ASC_APPLE_ID" \
    --password "$ASC_APP_PASSWORD" \
    --show-progress
fi

echo ""
echo "Upload complete. Build is processing on App Store Connect."
